import jsPDF from 'jspdf';
import { format } from 'date-fns';

const PAGE_MARGIN = 20;
const LINE_HEIGHT_TITLE = 7;
const LINE_HEIGHT_DESC = 5;
const LINE_HEIGHT_URL = 5;
const LINE_HEIGHT_META = 5;
const ARTICLE_SPACING = 10;
const SECTION_SPACING = 5;

const FONT_TITLE = { size: 14, color: [31, 41, 55] };
const FONT_DESC = { size: 10, color: [75, 85, 99] };
const FONT_SOURCE = { size: 9, color: [16, 185, 129] };
const FONT_URL = { size: 9, color: [59, 130, 246] };
const FONT_META = { size: 8, color: [156, 163, 175] };
const FONT_FOOTER = { size: 8, color: [156, 163, 175] };

const applyFont = (doc, font) => {
  doc.setFontSize(font.size);
  doc.setTextColor(...font.color);
};

const generatePDF = (selectedArticles) => {
  if (!selectedArticles || selectedArticles.length === 0) {
    alert('No articles selected for download');
    return;
  }

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - 2 * PAGE_MARGIN;
  let y = PAGE_MARGIN;

  doc.setFontSize(20);
  doc.setTextColor(16, 185, 129);
  doc.text('Thuthan - Renewable Energy News', pageWidth / 2, y, { align: 'center' });
  y += 10;

  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text(`Generated on: ${format(new Date(), 'PPP p')}`, pageWidth / 2, y, { align: 'center' });
  y += 15;

  doc.setDrawColor(16, 185, 129);
  doc.setLineWidth(0.5);
  doc.line(PAGE_MARGIN, y, pageWidth - PAGE_MARGIN, y);
  y += 10;

  selectedArticles.forEach((article, index) => {
    if (y > 250) {
      doc.addPage();
      y = PAGE_MARGIN;
    }

    applyFont(doc, FONT_TITLE);
    const titleLines = doc.splitTextToSize(`${index + 1}. ${article.title}`, contentWidth);
    doc.text(titleLines, PAGE_MARGIN, y);
    y += titleLines.length * LINE_HEIGHT_TITLE;

    if (article.description) {
      applyFont(doc, FONT_DESC);
      const descLines = doc.splitTextToSize(article.description, contentWidth);
      doc.text(descLines, PAGE_MARGIN, y);
      y += descLines.length * LINE_HEIGHT_DESC;
    }

    y += SECTION_SPACING;
    
    applyFont(doc, FONT_SOURCE);
    doc.text(`Source: ${article.source?.name || 'Unknown'}`, PAGE_MARGIN, y);
    y += LINE_HEIGHT_URL;
    
    applyFont(doc, FONT_URL);
    const url = article.url || article.link || '';
    const urlLines = doc.splitTextToSize(`Link: ${url}`, contentWidth);
    doc.text(urlLines, PAGE_MARGIN, y);
    y += urlLines.length * LINE_HEIGHT_URL;

    if (article.publishedAt) {
      y += SECTION_SPACING;
      applyFont(doc, FONT_META);
      doc.text(`Published: ${format(new Date(article.publishedAt), 'PPp')}`, PAGE_MARGIN, y);
      y += LINE_HEIGHT_META;
    }

    y += ARTICLE_SPACING;
    doc.setDrawColor(229, 231, 235);
    doc.line(PAGE_MARGIN, y, pageWidth - PAGE_MARGIN, y);
    y += ARTICLE_SPACING;
  });

  y += SECTION_SPACING;
  applyFont(doc, FONT_FOOTER);
  doc.text('Generated by Thuthan - Renewable Energy News Aggregator', pageWidth / 2, y, { align: 'center' });

  const filename = `thuthan-news-${format(new Date(), 'yyyy-MM-dd-HHmmss')}.pdf`;
  doc.save(filename);
};

export { generatePDF };
